### ISSUE TITLE
Positions not int

### ISSUE THREAD

**Issue by halge** [JobtechSwe/sokannonser-api#2]
curl  "http://sokannonser-api-sokapi.e4ff.pro-eu-west-1.openshiftapps.com/sok?dataset=arbetsf%C3%B6rmedlingen" -H  "accept: application/json" -H  "api-key: apa"
{"total": 9163, "positions": **16386.0,**

**Comment by mskold** [comment]
Mycket märkligt. Det är en int när den kommer från elastic, och det är en int när jag kör lokalt.

**Comment by mskold** [comment]
Verkar vara elastic-klienten som returnerar sum-aggregat som float. Fixat.
