### ISSUE TITLE
AttributeError: module 'sokannonser.settings' has no attribute 'EXPERIENCE_REQUIRED'

### ISSUE THREAD

**Issue by qeshi** [JobtechSwe/sokannonser-api#4]
När jag kör "flask run" så får jag

  File "sokannonser-api/sokannonser/rest/endpoint_platsannonser.py", line 39, in Search
    settings.EXPERIENCE_REQUIRED: "Visa enbart jobb som inte kräver erfarenhet",
AttributeError: module 'sokannonser.settings' has no attribute 'EXPERIENCE_REQUIRED'

**Comment by halge** [comment]
verified ok, fixed in https://github.com/JobtechSwe/sokannonser-api/commit/e42d3414b066f04173012c414852bd0ad5ea1061
