### ISSUE TITLE
Jobs with ID starting with 0019-

### ISSUE THREAD

**Issue by Inskrift** [JobtechSwe/sokannonser-api#53]
In old API some jobs has ID starting with "0019-". None of these jobs exists in new API.
Example: https://www.arbetsformedlingen.se/For-arbetssokande/Hitta-jobb/Platsbanken/annonser/0019-355285

**Comment by halge** [comment]
verified OK with https://github.com/JobtechSwe/sokannonser-api/commit/fec37ce6a3b26919f50769e36a3e70cd57b58178

**Comment by Inskrift** [comment]
I don't think this is "OK" - check the old API and you'll find a lot of jobs with ID starting with "0019-", even posted today. None of these can be find in new API still today. Maybe it is wrong ID on those jobs, I don't now, but those job isn't present under other ID, they can't be found at all if you search at https://www.arbetsformedlingen.se/For-arbetssokande/platsbanken/
