### ISSUE TITLE
taxonomy/search with type=skill

### ISSUE THREAD

**Issue by direktornswe** [JobtechSwe/sokannonser-api#66]
Would it be possible to search or link skills in the taxonomy API towards occupation-name, occupation-group or occupation-field? 

It would help to categorise a specific skill towards a specific occupation. 

I find some of the terms a bit confusion, as some contains a comma to define they are lets say "IT" focused. For example: 

            "conceptId": "Pk2j_jXV_Y3j",
            "id": "607589",
            "term": "Projektledning, IT",
            "typ": "kompetens",
            "type": "skill",
            "antal": 0
        }

But also exists: 
            "conceptId": "3TSx_fJE_Z26",
            "id": "2",
            "term": "Projektledning, erfarenhet",
            "typ": "kompetens",
            "type": "skill",
            "antal": 10
        }

At the moment its hard to distingues these two from each other.

**Comment by qeshi** [comment]
Hi!
We are working on a new api where it is possible to find relations between skills and occupation-group but it's still in beta.

Please contact support@jobtechdev.se and we can give you more information and help with your questions.
